{{- if .Values.clusterSecretStore.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault
  labels:
    "app.kubernetes.io/managed-by": Helm
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect:8080
      vaults:
        dev-env-overwrite: 1
        dev-env: 2
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-token
            key: token
            namespace: argocd

{{- end }}