apiVersion: v2
name: tekton
description: Tekton Helm Chart
maintainers:
  - name: Kununu Sparrow
version: 1.0.0
dependencies:
  - name: dashboard
    version: 0.6.4
    repository: https://eddycharly.github.io/tekton-helm
  - name: pipelines
    version: 0.12.0
    repository: https://eddycharly.github.io/tekton-helm
